name: plaid_transactions
description: Retrieve and view account information and transactions using the Plaid API
version: 0.0.1

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.2
  flutter_secure_storage: ^8.0.0
  http: ^0.13.5
  plaid_flutter: ^3.1.1
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

